### ISSUE TITLE
打包体积过大，如何处理？

### ISSUE THREAD

**Issue by vortesnail** [sixiaodong123/react-loading#43]
我本想只用其中一个组件，按照FAQ的第一个方式按需引用，打包出的体积比原项目多出400多K，请问怎么配置能使打的包小一点呢？

**Comment by sixiaodong123** [comment]
1. 第一种简单的方法就是 : import CommonLoading  from 'react-loadingg/lib/CommonLoading'; 这样的话只会把index.js 和 CommonLoading 以及utils打包进去, 其他的都不会打包进去 2.第二种方法的话需要配置一下你的webpack了,需要添加babel-plugin-import或者让你的项目支持 ES module 的 tree shaking.

**Comment by vortesnail** [comment]
我就是按你说的第一种方式，但是打包多出400多k应该不正常吧？ 

我先npm安装，然后按你说的第一种方式引入的

**Comment by sixiaodong123** [comment]
400多k应该不是这个组件库导致的, 这个组件库总共只有300k不到。我刚刚用create-react-app 测试了一下, 你用第一种方法的话,应该只会增加18k左右。
